project:
  type: website
  output-dir: docs

website:
  title: "Nurul Zahirah's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data-visualization.qmd
        text: Data Visualization

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true